//import "./globals.css";
import { Inter } from "next/font/google";
import { Footer } from "./components";
import StyledApp from "./components/StyledApp";
import { GlobalStyles } from "./styles/globalstyles";
import "normalize.css/normalize.css";
import StyledComponentsRegistry from "./lib/registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Architecture - Gallery",
  description: "Demo gallery generated by create next app hydrated by Unsplash",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <StyledApp>
      <StyledComponentsRegistry>
        <html lang="en">
          <GlobalStyles />
          <body className={inter.className}>
            {children}
            <Footer />
          </body>
        </html>
      </StyledComponentsRegistry>
    </StyledApp>
  );
};

RootLayout.displayName = "RootLayout";

export default RootLayout;
