import "./globals.css";
import { Inter } from "next/font/google";
import { Footer, Header, LayoutContainer } from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Architecture - Gallery",
  description: "Demo gallery generated by create next app hydrated by Unsplash",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>
          <LayoutContainer>{children}</LayoutContainer>
        </main>
        <Footer />
      </body>
    </html>
  );
}
